_BASE_: "Base-RCNN-FPN.yaml"
MODEL:
  # WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  # WEIGHTS: "/home/lingpeng/project/SparseR-CNN-main/model_final_a3ec72.pkl"  # 使用完全训练的mask R-CNN而不是单纯的backbone
  MASK_ON: True
  RESNETS:
    DEPTH: 101
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 270000